export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  const { email, role } = req.body;
  const userRole = role === 'parent' ? 'Parent' : 'Student';

  if (!email) {
    return res.status(400).json({ error: 'Email is required' });
  }

  // Tailored content based on role
  const subject = userRole === 'Parent' 
    ? 'Empowering Your Child’s Vision for WASSCE 2026 🎓' 
    : 'Welcome to the Vision Circle: Your WASSCE Mastery Starts Here 🎓';

  const heading = userRole === 'Parent'
    ? 'Academic Leadership for Parents'
    : 'Welcome to the Vision Circle';

  const intro = userRole === 'Parent'
    ? 'Thank you for joining Vision Education. As a parent, you play the most critical role in your child’s academic success. We are honored to partner with you to ensure they are fully prepared for the 2026 WASSCE.'
    : 'Welcome! You’ve just joined an exclusive community of Ghanaian students who are choosing to out-prepare, out-think, and out-perform. excellence is no longer a wish—it is a system.';

  const bulletPoints = userRole === 'Parent'
    ? `
      <li style="margin-bottom: 12px;"><strong>Monitoring Progress:</strong> Learn how to use our platform to track your child's mock scores in real-time.</li>
      <li style="margin-bottom: 12px;"><strong>Syllabus Insights:</strong> Stay updated on WAEC requirement changes that affect your child's preparation.</li>
      <li style="margin-bottom: 12px;"><strong>University Pathways:</strong> Get early insights into admission requirements for top institutions in Ghana and beyond.</li>
    `
    : `
      <li style="margin-bottom: 12px;"><strong>AI-Powered Insights:</strong> Be the first to receive study tips generated by our proprietary question-bank analysis.</li>
      <li style="margin-bottom: 12px;"><strong>Syllabus Alerts:</strong> Stay ahead of any 2026 WAEC changes before your peers even hear about them.</li>
      <li style="margin-bottom: 12px;"><strong>Mock Exam Drops:</strong> Get instant notifications whenever new subject mocks go live on the platform.</li>
    `;

  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: 'Vision Education <welcome@visionedu.site>',
        to: [email],
        reply_to: 'mensuohyaw@gmail.com',
        subject: subject,
        html: `
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <style>
              body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; margin: 0; padding: 0; background-color: #f8fafc; color: #1e293b; }
              .container { max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 24px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06); border: 1px solid #f1f5f9; }
              .header { background-color: #05080f; padding: 60px 40px; text-align: center; }
              .header-logo { width: 48px; height: 48px; background: linear-gradient(to bottom right, #10b981, #6366f1); border-radius: 12px; display: inline-flex; align-items: center; justify-content: center; color: white; font-weight: 800; font-size: 24px; margin-bottom: 24px; border: 1px solid rgba(255,255,255,0.1); }
              .header-text { color: #ffffff; font-size: 12px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.15em; margin: 0; opacity: 0.6; }
              .content { padding: 48px 40px; }
              .title { font-size: 28px; font-weight: 800; color: #0f172a; margin-bottom: 24px; line-height: 1.2; letter-spacing: -0.02em; }
              .paragraph { font-size: 16px; line-height: 1.6; color: #475569; margin-bottom: 24px; }
              .list { margin: 0 0 32px 0; padding: 0; list-style: none; }
              .button-container { text-align: center; margin-bottom: 40px; }
              .button { display: inline-block; padding: 16px 36px; background-color: #05080f; color: #ffffff; text-decoration: none; border-radius: 14px; font-weight: 700; font-size: 16px; }
              .footer { padding: 40px; border-top: 1px solid #f1f5f9; background-color: #ffffff; }
              .signature { font-size: 16px; line-height: 1.6; color: #64748b; }
              .signature-name { color: #0f172a; font-weight: 700; }
              .legal { font-size: 12px; color: #94a3b8; margin-top: 24px; line-height: 1.5; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <div class="header-logo">V</div>
                <p class="header-text">Vision Education GH</p>
              </div>
              <div class="content">
                <h1 class="title">${heading}</h1>
                <p class="paragraph">Hi,</p>
                <p class="paragraph">${intro}</p>
                <p class="paragraph">As a member of the Circle, you will receive exclusive updates on:</p>
                <ul class="list">
                  ${bulletPoints}
                </ul>
                <div class="button-container">
                  <a href="https://visionedu.site" class="button">Visit the Platform</a>
                </div>
                <div class="signature">
                  Best regards,<br>
                  <span class="signature-name">Yaw Ndaase Mensuoh</span><br>
                  Founder, Vision Education
                </div>
              </div>
              <div class="footer">
                <div class="legal">
                  You are receiving this because you signed up for updates via visionedu.site.<br>
                  Vision Education — Accra, Ghana.
                </div>
              </div>
            </div>
          </body>
          </html>
        `,
      }),
    });

    if (response.ok) {
      return res.status(200).json({ success: true });
    } else {
      const errorData = await response.json();
      return res.status(500).json({ error: errorData.message });
    }
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
